### ISSUE TITLE
How to run publish and subscribe in browser.Not from command prompt

### ISSUE THREAD

**Issue by sunilnimble2015** [bluerhinos/phpMQTT#49]
Hi 
Now i started to get message from publisher.But it possible only when i run it in terminal only.
Is it possible to run  it in the browser.And get message as it works inside terminal? I want that message should also get using browser....

**Comment by bendspoons** [comment]
Im not 100% sure, but i dont think it will work in any browser because of the continous running of the script. But you can e.g.call the php script via ajax with interval() or via Eventsource, for example:

<script type="text/javascript">
    if (!!window.EventSource) {
      var source = new EventSource('mqtt-steam.php');
    } else { // not availble
    }

    source.addEventListener('topic', function(e) {
      console.log(e.data);
    }, false);

    source.addEventListener('open', function(e) {
      // Connection was opened.
    }, false);

    source.addEventListener('error', function(e) {
      if (e.readyState == EventSource.CLOSED) {
        // Connection was closed.
      }
    }, false);
</script>

And in mqtt-stream.php just "echo" the data with following headers:

header('Content-Type: text/event-stream');
header('Cache-Control: no-cache'); // recommended to prevent caching of event data.

**Comment by bluerhinos** [comment]
Canned Response: Subscribe is not designed for web requests, it should be used in a long running process.
I do plan to add a subscribeAndWaitForMessage() function #95
